Skip to content

Search or jump to...
Pull requests
Issues
Codespaces
Marketplace
Explore
 
@sxz799 
sxz799
/
gsCheck
Public
Cannot fork because you own this repository and are not a member of any organizations.
Code
Issues
Pull requests
Actions
Projects
Wiki
Security
Insights
Settings
Node.js CI
Update node.js.yml #4
Jobs
Run details
Workflow file for this run
.github/workflows/node.js.yml at a27478c
# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: ls
    - run: cd web/
    - run: ls
    - run: npm ci
    - run: npm run build --if-present
    - run: ls
    - name: Download a Build Artifact
      uses: actions/download-artifact@v2.1.1
      with:
       name:  gscheck-web-githubAction-artifact
       path: ${{ github.workspace }}/web/dist
Update node.js.yml · sxz799/gsCheck@a27478c 
