# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: [main]


jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        
    - name: Build
      run: npm install && npm run build
      working-directory: ./web

    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
       name: dist-artifact
       path: ${{ github.workspace }}/web/dist

    - name: Download a Build Artifact
      uses: actions/download-artifact@v2.1.1
      with:
       name: dist-artifact
       path: ${{ github.workspace }}/web/dist
    
